DOMAIN = "hp_aruba_switch"
CONF_HOST = "host"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_EXCLUDE_PORTS = "exclude_ports"
CONF_EXCLUDE_POE = "exclude_poe"
CONF_SSH_PORT = "ssh_port"
CONF_PORT_COUNT = "port_count"
